### PR TITLE
Titan Edition

### PR DESCRIPTION
**Pull request by MegaPiggy**
From @Minecraft633

### CODE REVIEW

**Comment by Minecraft633** [comment]
Alright so basically this is probably gonna be the original RSS's revival

**Comment by MegaPiggy** [comment]
I mean it was already being revived a bit in the [lore](https://github.com/xen-42/outer-wilds-real-solar-system/tree/lore) branch

**Comment by Minecraft633** [comment]
Alright, so my fork will be merged with the main branch, and the lore branch will be kept the way it is right now

**Comment by TerrificTrifid** [comment]
Fyi, I think only the neptune texture and polish translation will end up surviving, as the lore branch is a pretty extensive overhaul. I appreciate the effort though, and don't blame you for not knowing about the revamp barely in progress for almost two years :P

**Comment by Minecraft633** [comment]
I think that we should make a new "overhaul" branch which is basically titan edition, and yes i will add my things like the ship log icons and lore and easter eggs and more

**Comment by MegaPiggy** [comment]
Where did you find the venus texture?

**Pull request merged**
